import Link from "next/link";
import { sponsorshipPlans } from "../../lib/monetization";

export default async function AdvertisePage({ searchParams }: { searchParams: Promise<{ sent?: string }> }) {
  const query = await searchParams;
  return <main>
    <header className="topbar"><Link className="brand" href="/">DataCenter<span>.forum</span></Link><nav><Link href="/vendors">Vendors</Link><Link href="/jobs">Jobs</Link><Link href="/partners">Partners</Link></nav></header>
    <section className="commerceHero"><span className="kicker">SPONSORSHIP & INDUSTRY MARKETING</span><h1>Reach the people specifying, buying, building, and operating.</h1><p>Commercial programs sit around the conversation, never inside member trust. Every paid placement is labeled. Sponsors cannot purchase positive coverage, moderation outcomes, rankings, or access to private member data.</p><div className="heroActions"><a className="buttonLink" href="#inquire">Request a package</a><Link href="/partners">Founding Partner program →</Link></div></section>
    <section className="section darkSection"><div className="sectionHead"><div><span className="kicker">PACKAGES</span><h2>High-value, low-clutter inventory</h2></div></div><div className="pricingGrid">{sponsorshipPlans.map(plan => <article className="priceCard" key={plan.name}><span>{plan.name}</span><h3>{plan.price}</h3><p>{plan.name === "Category Sponsor" ? "Own clearly labeled visibility around one focused practitioner category." : plan.name === "Sponsored Briefing" ? "A disclosed research, webinar, AMA, or briefing package built around a real industry question." : "Custom research and structured market intelligence with explicit sponsor disclosure."}</p><a href="#inquire">Discuss package →</a></article>)}</div></section>
    <section className="section"><div className="principleGrid"><article><span>01</span><h3>Disclosure is permanent</h3><p>Sponsored content stays labeled wherever it is reused or indexed.</p></article><article><span>02</span><h3>No pay-to-rank</h3><p>Commercial spend does not control organic search, forum ranking, or member sentiment.</p></article><article><span>03</span><h3>No private-data resale</h3><p>Buyer introductions require explicit user intent and consent.</p></article><article><span>04</span><h3>Measure business outcomes</h3><p>Lead requests, qualified introductions, event registrations, and engagement matter more than raw impressions.</p></article></div></section>
    <section id="inquire" className="section commerceSplit"><div><span className="kicker">SALES INQUIRY</span><h2>Tell us what you need to move</h2><p>Pipeline, market education, hiring, category awareness, or a specific launch. We will keep the commercial package narrow enough to measure.</p>{query.sent === "1" && <p className="successNotice">Inquiry received.</p>}</div><form className="commerceForm" action="/api/sponsorship-inquiries" method="post"><label>Company<input name="company_name" required /></label><label>Your name<input name="contact_name" required /></label><label>Work email<input name="contact_email" type="email" required /></label><label>Package<select name="package" defaultValue="Category Sponsor">{sponsorshipPlans.map(plan => <option key={plan.name}>{plan.name}</option>)}</select></label><label>Budget range<input name="budget" placeholder="$1,500–$5,000" /></label><label>Goal<textarea name="notes" minLength={10} maxLength={3000} required /></label><button type="submit">Request sponsorship package</button></form></section>
  </main>;
}
